sudo: true
language: python
python:
  - "2.7"
install:
  - pip install pybuilder coveralls
  - pyb -v install_dependencies
before_script:
  - sudo apt-get update
  - sudo apt-get install python-svn
  - ln -s /usr/lib/python2.7/dist-packages/pysvn $VIRTUAL_ENV/lib/python2.7/site-packages/
script:
  - pyb -v verify analyze
after_success:
  - coveralls --verbose
