dist: bionic
sudo: true
language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install pybuilder coveralls
  - pyb -v install_dependencies
before_script:
  - sudo apt-get update
  - sudo apt-get install python3-svn
  - ln -s /usr/lib/python3.5.7/dist-packages/pysvn $VIRTUAL_ENV/lib/python3/site-packages/
script:
  - pyb -v verify analyze
after_success:
  - coveralls --verbose
